create table TEMPLATE(
	TEMPLATE_ID UUID PRIMARY KEY,
	NAME VARCHAR(200) NOT NULL,
	TITLE VARCHAR(200) NOT NULL,
	SUB_TITLE VARCHAR(500) NOT NULL
);

create table TEMPLATE_ROW(
	ROW_ID UUID PRIMARY KEY,
	TEMPLATE_ID UUID NOT NULL CONSTRAINT ROW_FK references TEMPLATE ON DELETE CASCADE
);

create table TEMPLATE_COLUMN(
	COLUMN_ID UUID PRIMARY KEY,
	COLUMN_TYPE VARCHAR(50),
	TYPE_VALUE VARCHAR(1000),
	ROW_ID UUID NOT NULL CONSTRAINT COLUMN_FK references TEMPLATE_ROW ON DELETE CASCADE
);